apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo1-system
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    system: demo1
spec:
  project: default
  source:
    repoURL: https://github.com/llowinge/demo1-system.git
    path: "."
    directory:
      include: "*/*.yaml"
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=false
    retry:
      limit: 0
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m